---
- name: cloning repo
  hosts: webservers
  gather_facts: no
  vars_files:
     - vault2.yml

  tasks: 
  - name: cloning repo
    git: 
      repo: https://baprossy:{{ git_password }}@github.com/baprossy/vaultset.git
      dest: /home/ansadmin/vaultest

